### PR TITLE
Enable wayland

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Updates the packaging so that scummvm can and will launch under Wayland when possible, and does not rely on X11 support.

### CODE REVIEW

**Comment by lotharsm** [comment]
Hi @AlanGriffiths, ScummVM dev here. Thanks a lot for your contribution! I just checked the changes you made and I can happily report that it runs without issues or regressions.

Our snap package is currently missing support for speech-dispacher, but if I unserstand correctly, the "deamonizing" stuff you added for wayland could be very helpful here.

Thank you!

**Comment by AlanGriffiths** [comment]
Hi @lotharsm, I don't know anything about speech-dispacher, but I don't see how the  "deamonizing" stuff would be relevant.

FYI I'm trying to integrate enough from https://github.com/MirServer/mir-kiosk-scummvm so that this snap works on core systems. There's no point in maintaining both packages. Making the Wayland backend work is the first step.

**Comment by lotharsm** [comment]
> Hi @lotharsm, I don't know anything about speech-dispacher, but I don't see how the "deamonizing" stuff would be relevant.
> 

From what I understand is that speech-dispatcher needs a libspeechd-daemon running. Currently, that's not possible since the Snap can't communicate with the speechd-socket on the "host" system. I already tried it with `devmode`, but without success.

> FYI I'm trying to integrate enough from https://github.com/MirServer/mir-kiosk-scummvm so that this snap works on core systems. There's no point in maintaining both packages. Making the Wayland backend work is the first step.

Sounds great, looking forward to it :)

**Comment by AlanGriffiths** [comment]
> From what I understand is that speech-dispatcher needs a libspeechd-daemon running. Currently, that's not possible since the Snap can't communicate with the speechd-socket on the "host" system. I already tried it with `devmode`, but without success.

You're thinking of adding a libspeechd-daemon to the snap? That would be something completely separate to the changes here.

Regardless, it seems odd that you can't get that to work in devmode. What is the socket you need to connect to on the host system? If, for example, it lives under $XDG_RUNTIME_DIR then there may be some "magic" needed (like there is for the Wayland socket).

> Sounds great, looking forward to it :)

The next PR is ready once this one lands. :)

**Comment by lotharsm** [comment]
> You're thinking of adding a libspeechd-daemon to the snap? That would be something completely separate to the changes here.

Yes, exactly. Well, seems that I'm on the wrong track here - blame my lack of experience with snapping ;)

> 
> Regardless, it seems odd that you can't get that to work in devmode. What is the socket you need to connect to on the host system? If, for example, it lives under $XDG_RUNTIME_DIR then there may be some "magic" needed (like there is for the Wayland socket).
> 

Well, I don't know exactly what I did wrong here, but no matter if I used devmode or not, it always complined. I haven't tried it again since then, but somehow, it expected the speechd socket to "live" insinde the snap directory...

**Comment by AlanGriffiths** [comment]
> Well, I don't know exactly what I did wrong here, but no matter if I used devmode or not, it always complined. I haven't tried it again since then, but somehow, it expected the speechd socket to "live" insinde the snap directory...

A quick search found this:

> For local communication, it’s preferred to use Unix sockets, where the communication takes place over a Unix socket with its driving file located by default in the user’s runtime directory as XDG_RUNTIME_DIR/speech-dispatcher/speechd.sock.

And snaps have `XDG_RUNTIME_DIR` set to a snap specific dir. That suggests you'd need:

```plain
mkdir -p $XDG_RUNTIME_DIR/speech-dispatcher
ln -sf "$(dirname $XDG_RUNTIME_DIR)/speech-dispatcher/speechd.sock" "$XDG_RUNTIME_DIR/speech-dispatcher/speechd.sock"
```
In a launch script somewhere. If that works in devmode, then any other problems are a matter of getting the interfaces right.

**Comment by lotharsm** [comment]
> In a launch script somewhere. If that works in devmode, then any other problems are a matter of getting the interfaces right.

Hi there, thanks for the feedback. I don't want to derail this PR too much, but I tried to add what you suggested to the launch-script. Even in devmode, this is what I get:
```mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/run/user/0/snap.snapcraft/speech-dispatcher/speechd.sock': No such file or directory
WARNING: Couldn't initialize text to speech through speech-dispatcher!
```

Both libspeechd2 and speech-dispatcher are added to the stage packages.

**Comment by AlanGriffiths** [comment]
> I don't want to derail this PR too much

Is anything needed to get this PR landed?

**Comment by lotharsm** [comment]
From my side, this is ready to roll. Thanks a lot!

**Comment by AlanGriffiths** [comment]
> From my side, this is ready to roll. Thanks a lot!

It needs someone with write access to land it. @popey?

**Comment by lotharsm** [comment]
@popey to the rescue! :)

**Pull request merged**
